enum {
	KEY_TRIP = 0x0,
	KEY_LOCATION = 0x1,
	KEY_LOG_SPECIES = 0x2,
	KEY_LOG_SPECIES_NAME = 0x3,
	KEY_LOG_WEIGHT_POUND = 0x4,
	KEY_LOG_WEIGHT_OUNCE = 0x5,
	KEY_LOG_LENGTH_FEET = 0x6,
	KEY_LOG_LENGTH_INCH = 0x7
};